version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # create tickets in the middle of the day
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Europe/London"
    # ignore patch versions (until we deal with the backlog)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "dep"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dep"
