name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    name: Build, Lint and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: pnpm/action-setup@v2
      with:
          version: 8.8.0
    - uses: actions/setup-node@v4
      with:
          node-version-file: ".node-version"
          cache: "pnpm"

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint

    - name: Prettier Check
      run: pnpm format:check

    - name: Check Types
      run: pnpm check-types